config/routes.rb
Rails.application.routes.draw do
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  get 'static_pages/home'
  get 'static_pages/about'
  get 'static_pages/help'
root 'static_pages#home' 
  resources :incomes
  resources :users

end

app/models/income.rb
class Income < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_one :income, dependent: :destroy
  before_save  {self.mortgage_reference_num = mortgage_reference_num.upcase}  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :mortgage_reference_num, presence: true, uniqueness: {case_sensitive: false}
  
  has_secure_password
  validates  :password, presence: true, length: {minimum: 6}
  
  
  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  


  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  include UsersHelper
  
  before_action :require_login
  
  private
  def require_login
    unless logged_in?
      flash[:error] = "Please Log In"
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  
  def new
  end
  
  def create
    user = User.find_by(mortgage_reference_num: params[:sessions][:mortgage_reference_num].upcase)
    if user && user.authenticate(params[:sessions][:password])
      log_in(user)
      unless user.admin?
      redirect_to income_path(id: Income.find_by(user_id: user.id).id)
      else
        redirect_to incomes_path
      end
    else
      flash.now[:danger] = 'Invalid Mortgage Reference # or Password combination'
      render 'new'
    end
  end
    
  def destroy
    log_out
    redirect_to root_path
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login
  
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :admin_user?, only: [:index, :new, :create, :delete, :destroy]
  
  
  def index
    @users = Users.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save && !@user.admin?
      @income = @user.create_income(user_id: @user.id)
      flash[:success] = "New User Created"
      redirect_to(:action => 'show', :id => @user.id)

    else
      render 'new'
    end

  end

  
  def delete
  end
  
  def destroy
  end
  
  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :mortgage_reference_num,  :password, :password_confirmation)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/incomes_helper.rb
module IncomesHelper
  
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
# Logs in the given user.
  
  def log_in(user)
    session[:user_id] = user.id
  end 
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
 
  
  
  #checks admin status
  def admin_user?
    if logged_in?
      unless current_user.admin?
      redirect_to root_path
      end
    end
  end
  

  #checks user can only view their income, and no one elses, unless admin. 
def myincome?
  unless current_user.admin? || (Income.find_by(user_id: current_user.id).id == @income.id)
    redirect_to root_path      
    end   
end
    
 
end

app/views/incomes/_incomeform.html.erb
<%= simple_form_for @income do |f| %>  

  <H1>Income</H1>
  <H2>Salary or Wages</h2>
  <p>
    <%= f.input :clients_salary_wages, label: 'Monthly salary or wage, after tax' %>
    <%= f.input :partners_salary_wages, label: 'Partner\'s salary or wage, after tax' %>
    <%= f.input :other_income, label: 'Other income' %>
</p>

  <H2>Other Income</H2>
<p>
    <%= f.input :maintenance_childsupport, label: 'Maintenance or child support' %>
    <%= f.input :boarders_lodgers, label: 'Boarders or Lodgers' %>
    <%= f.input :non_dependant_contributions, label: 'Non dependant contributions' %>
    <%= f.input :student_loans_grants, label: 'Student loans and grants' %>
    <%= f.input :other_other_income, label: 'Other Income' %>
  </p>

  <H2>Benefits</H2> 
<p>
    <%= f.input :jobseekers_allowance_income, label: 'Jobseeker\'s Allowance (Income-based)' %>
    <%= f.input :jobseekers_allowance_contribution, label: 'Jobseeker\'s Allowance (Contribution-based)' %>
    <%= f.input :income_support, label: 'Income Support' %>
    <%= f.input :working_tax_credit, label: 'Working Tax Credit' %>
    <%= f.input :child_tax_credit, label: 'Child Tax Credit' %>
    <%= f.input :child_benefit, label: 'Child Benefit' %>
    <%= f.input :employment_support_allowance_statutory_sickpay, label: 'Employment & Support Allowance / Statutory Sick Pay' %>
    <%= f.input :dla_pip_attendance_allowance, label: 'DLA, PIP or Attendance Allowance' %>
    <%= f.input :carers_allowance, label: 'Carer\'s Allowance' %>
    <%= f.input :housing_benefit_local_housing_allowance, label: 'Housing Benefit / Local Housing Allowance' %>
    <%= f.input :council_tax_reduction, label: 'Council Tax Reduction' %>
    <%= f.input :other_including_universal_credit, label: 'Other (including Universal Credit)' %>
    <%= f.input :other_benefits, label: 'Other benefits' %>
  </p>

  <H2>Pensions</H2>
<p>
    <%= f.input :state_pensions, label: 'State pension(s)' %>
    <%= f.input :private_workpensions, label: 'Private or work pension(s)' %>
    <%= f.input :pension_credit, label: 'Pension Credit' %>
    <%= f.input :other_pension, label: 'Other' %>
  </p>

<h1>Assets and Equity</h1>
  <H2>House or Flat</H2>
<p>
    <%= f.input :total_value_propertyies, label: 'Monthly Total Income' %>
    <%= f.input :mortgage_outstanding, label: 'Mortgage outstanding' %>
    <%= f.input :secured_loans_outstanding, label: 'Secured loan(s) outstanding' %>
</p>

  <H2>Other Assets</H2>  
<p>
    <%= f.input :value_vehicles_less_hpoutstanding, label: 'Value of vehicle(s) (less HP outstanding)' %>
    <%= f.input :savings, label: 'Savings' %>
    <%= f.input :otherassets, label: 'Other assets' %>
  </p>

  <H1>Expenditure</H1>
  <H2>Essential Expenditure</H2>
<p>
    <%= f.input :rent, label: 'Rent' %>
    <%= f.input :ground_rent_service_charges_factor_fees, label: 'Ground rent, service charges, factor fees ' %>
    <%= f.input :mortgage, label: 'Mortgage' %>
    <%= f.input :other_secured_loans, label: 'Other secured loans ' %>
    <%= f.input :mortgage_endowment_mortgage_ppi, label: 'Mortgage Endowment / Mortgage PPI' %>
    <%= f.input :building_and_contents_insurance, label: 'Building and contents insurance' %>
    <%= f.input :pension_and_life_insurance, label: 'Pension and life insurance' %>
    <%= f.input :council_tax_rates_in_ni, label: 'Council Tax (Rates in NI)' %>
    <%= f.input :gas, label: 'Gas' %>
    <%= f.input :electricity, label: 'Electricity' %>
    <%= f.input :water_na_in_scotland_or_ni, label: 'Water (N/A in Scotland or NI)' %>
    <%= f.input :other_utilities_coal_oil_calor_gas, label: 'Other utilities (coal, oil, calor gas)' %>
    <%= f.input :tv_licence, label: 'TV licence' %>
    <%= f.input :magistrates_or_sheriff_court_fines, label: 'Magistrates\' or sheriff court fines' %>
    <%= f.input :maintenance_or_child_support, label: 'Maintenance or child support' %>
    <%= f.input :hire_purchase_conditional_sale, label: 'Hire Purchase / Conditional Sale' %>
    <%= f.input :childcare_costs, label: 'Childcare costs' %>
    <%= f.input :adult_care_costs, label: 'Adult care costs' %>
    <%= f.input :other_essential1, label: 'Other' %>
    <%= f.input :other_essenttial2, label: 'Other' %>
    <%= f.input :other_essential3, label: 'Other' %>
   </p>

  <H2>Phone</H2>
<p>
  <%= f.input :home_phone, label: 'Home phone' %>
    <%= f.input :mobile_phone, label: 'Mobile phone' %>
    <%= f.input :other_phone, label: 'Other phone' %>
  </p>

  <H2>Travel</H2>
<p>
    <%= f.input :monthly_total_phone, label: 'Monthly Total Phone' %>
    <%= f.input :public_transport_work_school_shopping_etc, label: 'Public transport (work, school, shopping etc)' %>
    <%= f.input :other_transport, label: 'Other (e.g. taxis)' %>
    <%= f.input :car_insurance, label: 'Car insurance' %>
    <%= f.input :vehicle_tax, label: 'Vehicle Tax' %>
    <%= f.input :fuel_petrol_diesel_oil_etc, label: 'Fuel (Petrol, Diesel, Oil etc)' %>
    <%= f.input :mot_and_car_maintenance, label: 'MOT and car maintenance' %>
    <%= f.input :breakdown_or_recovery, label: 'Breakdown or recovery' %>
    <%= f.input :parking_charges_or_tolls, label: 'Parking charges or tolls' %>
    <%= f.input :other_car_costs, label: 'Other car costs' %>
</p>

  <H2>House Keeping</H2>
<p>
    <%= f.input :food_and_milk, label: 'Food and milk' %>
    <%= f.input :cleaning_and_toiletries, label: 'Cleaning and toiletries' %>
    <%= f.input :newspapers_and_magazines, label: 'Newspapers and magazines' %>
    <%= f.input :cigarettes_tobacco_sweets, label: 'Cigarettes, tobacco & sweets' %>
    <%= f.input :alcohol, label: 'Alcohol' %>
    <%= f.input :laundry_and_dry_cleaning, label: 'Laundry and dry cleaning' %>
    <%= f.input :clothing_and_footwear, label: 'Clothing and footwear' %>
    <%= f.input :nappies_and_baby_items, label: 'Nappies and baby items' %>
    <%= f.input :pet_food, label: 'Pet food' %>
    <%= f.input :other_housekeeping, label: 'Other housekeeping' %>
</p>

  <H2>Other Expenditure</H2>
<p>
    <%= f.input :health_dentist_glasses_prescriptions_health_ins, label: 'Health (dentist, glasses, prescriptions, health ins)' %>
    <%= f.input :repairs_house_maint_incl_window_cleaning_maint_contracts, label: 'Repairs / house maint (incl window cleaning, maint contracts)' %>
    <%= f.input :hairdressing_haircuts, label: 'Hairdressing / haircuts' %>
    <%= f.input :cable_satellite_and_internet, label: 'Cable, Satellite and Internet ' %>
    <%= f.input :tv_video_and_other_appliance_rental, label: 'TV, video and other appliance rental' %>
    <%= f.input :school_meals_and_meals_at_work, label: 'School meals and meals at work' %>
    <%= f.input :pocket_money_and_school_trips, label: 'Pocket money and school trips' %>
    <%= f.input :lottery_and_pools_etc, label: 'Lottery and pools etc' %>
    <%= f.input :hobbies_leisure_sport_incl_puboutings_gym_etc, label: 'Hobbies, leisure, sport including pub outings, gym etc)' %>
    <%= f.input :gifts_christmas_birthdays_charity_etc, label: 'Gifts (Christmas, birthdays, charity etc)' %>
    <%= f.input :vet_bills_and_pet_insurance, label: 'Vet bills and pet insurance' %>
    <%= f.input :other_expenditure1, label: 'Other (e.g. postage)' %>
    <%= f.input :other_expenditure2, label: 'Other (e.g. holidays)' %>
</p>

<%= f.submit "Save and Proceed",  class:"mybutton" %>
<% end %>
<p>You will have a chance to review your form before you submit it.  Once you click Save, you can come back and complete the rest of the form at a later date</p>

app/views/incomes/edit.html.erb
<% provide(:title, "Edit Your Data") %>
<div class="innerpage">
  <h3>Here is the saved data, for XXXX XXXX (enter user.first).  Remember to click save to store your progress.</h3>

  <%= render 'incomeform', url: income_path(@income), method: :patch %>

  <%= link_to 'Back', :back %>

</div>

app/views/incomes/index.html.erb
<% provide(:title, "All data") %>
<div>
  <p id="notice"><%= notice %></p>
<%= link_to 'Add New User', new_user_path, class: "button radius"%> 
  
  <h1>Listing Users</h1>

  <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <%@incomes.each do |income| %>
        <tr>
          <td><%unless User.find_by(id: income.user_id).admin?%>
                <%=income.id%>
            <%else%>
            Admin
            <%end%></td>
          <td><%=User.find_by(id: income.user_id).first_name %></td>
          <td><%=User.find_by(id: income.user_id).last_name %></td>
          <td><%= link_to 'Show', income_path(income) %></td>
          <td><%= link_to 'Edit', edit_income_path(income) %></td>
          <td><%= link_to 'Delete', income_path(income), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>


</div>

app/views/incomes/show.html.erb
<% provide(:title, "Your Saved Data") %>
<div>
  <h3>Here is the saved data, for <%=User.find_by(id: @income.user_id).first_name %> <%=User.find_by(id: @income.user_id).last_name %>.</h3>

  <p><h4><%= link_to 'Edit your details', edit_income_path(@income) %></h4></p>

  
  <p>
  <strong>Your monthly salary or wage, after tax:</strong>
    <%= @income.clients_salary_wages %></p>
  <p><strong>Your partner’s salary or wage, after tax:</strong>
    <%= @income.partners_salary_wages %></p>
  <p><strong>Other income:</strong>
    <%= @income.other_income %></p>
  <p><strong>Maintenance or child support:</strong>
    <%= @income.maintenance_childsupport %></p>
  <p><strong>Boarders or Lodgers:</strong>
    <%= @income.boarders_lodgers %></p>
  <p><strong>Non dependant contributions:</strong>
    <%= @income.non_dependant_contributions %></p>
  <p><strong>Student loans and grants:</strong>
    <%= @income.student_loans_grants %></p>
  <p><strong>Other Income:</strong>
    <%= @income.other_other_income %></p>
  <p><strong>Jobseeker’s Allowance (Income-based):</strong>
    <%= @income.jobseekers_allowance_income %></p>
  <p><strong>Jobseeker’s Allowance (Contribution-based):</strong>
    <%= @income.jobseekers_allowance_contribution %></p>
  <p><strong>Income Support:</strong>
    <%= @income.income_support %></p>
  <p><strong>Working Tax Credit:</strong>
    <%= @income.working_tax_credit %></p>
  <p><strong>Child Tax Credit:</strong>
    <%= @income.child_tax_credit %></p>
  <p><strong>Child Benefit:</strong>
    <%= @income.child_benefit %></p>
  <p><strong>Employment & Support Allowance / Statutory Sick Pay:</strong>
    <%= @income.employment_support_allowance_statutory_sickpay %></p>
  <p><strong>DLA, PIP or Attendance Allowance:</strong>
    <%= @income.dla_pip_attendance_allowance %></p>
  <p><strong>Carer’s Allowance:</strong>
    <%= @income.carers_allowance %></p>
  <p><strong>Housing Benefit / Local Housing Allowance:</strong>
    <%= @income.housing_benefit_local_housing_allowance %></p>
  <p><strong>Council Tax Reduction:</strong>
    <%= @income.council_tax_reduction %></p>
  <p><strong>Other (including Universal Credit):</strong>
    <%= @income.other_including_universal_credit %></p>
  <p><strong>Other benefits:</strong>
    <%= @income.other_benefits %></p>
  <p><strong>State pension(s):</strong>
    <%= @income.state_pensions %></p>
  <p><strong>Private or work pension(s):</strong>
    <%= @income.private_workpensions %></p>
  <p><strong>Pension Credit:</strong>
    <%= @income.pension_credit %></p>
  <p><strong>Other:</strong>
    <%= @income.other_pension %></p>
  <p><strong>Monthly Total Income:</strong>
    <%= @income.total_value_propertyies %></p>
  <p><strong>Mortgage outstanding:</strong>
    <%= @income.mortgage_outstanding %></p>
  <p><strong>Secured loan(s) outstanding:</strong>
    <%= @income.secured_loans_outstanding %></p>
  <p><strong>Value of vehicle(s) (less HP outstanding):</strong>
    <%= @income.value_vehicles_less_hpoutstanding %></p>
  <p><strong>Savings:</strong>
    <%= @income.savings %></p>
  <p><strong>Other assets:</strong>
    <%= @income.otherassets %></p>
  <p><strong>Rent:</strong>
    <%= @income.rent %></p>
  <p><strong>Ground rent, service charges, factor fees :</strong>
    <%= @income.ground_rent_service_charges_factor_fees %></p>
  <p><strong>Mortgage:</strong>
    <%= @income.mortgage %></p>
  <p><strong>Other secured loans :</strong>
    <%= @income.other_secured_loans %></p>
  <p><strong>Mortgage Endowment / Mortgage PPI:</strong>
    <%= @income.mortgage_endowment_mortgage_ppi %></p>
  <p><strong>Building and contents insurance:</strong>
    <%= @income.building_and_contents_insurance %></p>
  <p><strong>Pension and life insurance:</strong>
    <%= @income.pension_and_life_insurance %></p>
  <p><strong>Council Tax (Rates in NI):</strong>
    <%= @income.council_tax_rates_in_ni %></p>
  <p><strong>Gas:</strong>
    <%= @income.gas %></p>
  <p><strong>Electricity:</strong>
    <%= @income.electricity %></p>
  <p><strong>Water (N/A in Scotland or NI):</strong>
    <%= @income.water_na_in_scotland_or_ni %></p>
  <p><strong>Other utilities (coal, oil, calor gas):</strong>
    <%= @income.other_utilities_coal_oil_calor_gas %></p>
  <p><strong>TV licence:</strong>
    <%= @income.tv_licence %></p>
  <p><strong>Magistrates’ or sheriff court fines:</strong>
    <%= @income.magistrates_or_sheriff_court_fines %></p>
  <p><strong>Maintenance or child support:</strong>
    <%= @income.maintenance_or_child_support %></p>
  <p><strong>Hire Purchase / Conditional Sale:</strong>
    <%= @income.hire_purchase_conditional_sale %></p>
  <p><strong>Childcare costs:</strong>
    <%= @income.childcare_costs %></p>
  <p><strong>Adult care costs:</strong>
    <%= @income.adult_care_costs %></p>
  <p><strong>Other:</strong>
    <%= @income.other_essential1 %></p>
  <p><strong>Other:</strong>
    <%= @income.other_essenttial2 %></p>
  <p><strong>Other:</strong>
    <%= @income.other_essential3 %></p>
  <p><strong>Home phone:</strong>
    <%= @income.home_phone %></p>
  <p><strong>Mobile phone:</strong>
    <%= @income.mobile_phone %></p>
  <p><strong>Other phone:</strong>
    <%= @income.other_phone %></p>
  <p><strong>Monthly Total Phone:</strong>
    <%= @income.monthly_total_phone %></p>
  <p><strong>Public transport (work, school, shopping etc):</strong>
    <%= @income.public_transport_work_school_shopping_etc %></p>
  <p><strong>Other (e.g. taxis):</strong>
    <%= @income.other_transport %></p>
  <p><strong>Car insurance:</strong>
    <%= @income.car_insurance %></p>
  <p><strong>Vehicle Tax:</strong>
    <%= @income.vehicle_tax %></p>
  <p><strong>Fuel (Petrol, Diesel, Oil etc):</strong>
    <%= @income.fuel_petrol_diesel_oil_etc %></p>
  <p><strong>MOT and car maintenance:</strong>
    <%= @income.mot_and_car_maintenance %></p>
  <p><strong>Breakdown or recovery:</strong>
    <%= @income.breakdown_or_recovery %></p>
  <p><strong>Parking charges or tolls:</strong>
    <%= @income.parking_charges_or_tolls %></p>
  <p><strong>Other car costs:</strong>
    <%= @income.other_car_costs %></p>
  <p><strong>:</strong>
    <%= @income.monthly_total_travel %></p>
  <p><strong>Food and milk:</strong>
    <%= @income.food_and_milk %></p>
  <p><strong>Cleaning and toiletries:</strong>
    <%= @income.cleaning_and_toiletries %></p>
  <p><strong>Newspapers and magazines:</strong>
    <%= @income.newspapers_and_magazines %></p>
  <p><strong>Cigarettes, tobacco & sweets:</strong>
    <%= @income.cigarettes_tobacco_sweets %></p>
  <p><strong>Alcohol:</strong>
    <%= @income.alcohol %></p>
  <p><strong>Laundry and dry cleaning:</strong>
    <%= @income.laundry_and_dry_cleaning %></p>
  <p><strong>Clothing and footwear:</strong>
    <%= @income.clothing_and_footwear %></p>
  <p><strong>Nappies and baby items:</strong>
    <%= @income.nappies_and_baby_items %></p>
  <p><strong>Pet food:</strong>
    <%= @income.pet_food %></p>
  <p><strong>Other housekeeping:</strong>
    <%= @income.other_housekeeping %></p>
  <p><strong>:</strong>
    <%= @income.monthly_total_housekeeping %></p>
  <p><strong>Health (dentist, glasses, prescriptions, health ins):</strong>
    <%= @income.health_dentist_glasses_prescriptions_health_ins %></p>
  <p><strong>Repairs / house maint (incl window cleaning, maint contracts):</strong>
    <%= @income.repairs_house_maint_incl_window_cleaning_maint_contracts %></p>
  <p><strong>Hairdressing / haircuts:</strong>
    <%= @income.hairdressing_haircuts %></p>
  <p><strong>Cable, Satellite and Internet :</strong>
    <%= @income.cable_satellite_and_internet %></p>
  <p><strong>TV, video and other appliance rental:</strong>
    <%= @income.tv_video_and_other_appliance_rental %></p>
  <p><strong>School meals and meals at work:</strong>
    <%= @income.school_meals_and_meals_at_work %></p>
  <p><strong>Pocket money and school trips:</strong>
    <%= @income.pocket_money_and_school_trips %></p>
  <p><strong>Lottery and pools etc:</strong>
    <%= @income.lottery_and_pools_etc %></p>
  <p><strong>Hobbies / leisure / sport  (incl pub/outings, gym etc):</strong>
    <%= @income.hobbies_leisure_sport_incl_puboutings_gym_etc %></p>
  <p><strong>Gifts (Christmas, birthdays, charity etc):</strong>
    <%= @income.gifts_christmas_birthdays_charity_etc %></p>
  <p><strong>Vet bills and pet insurance:</strong>
    <%= @income.vet_bills_and_pet_insurance %></p>
  <p><strong>Other (e.g. postage):</strong>
    <%= @income.other_expenditure1 %></p>
  <p><strong>Other (e.g. holidays):</strong>
    <%= @income.other_expenditure2 %></p>





  </p>
</div>

app/views/layouts/_footer.html.erb
<div class="row">
     <!--div class="small-11 small-centered  columns" !-->
     <div class="footer">
<p>Created by o-bot-laboratoy</p>
     </div>
  <!--/div !-->
</div>

app/views/layouts/_messages.html.erb
<div>
  <% if logged_in? %>
  <p> You are logged in as: <%= @current_user.first_name %> <%= @current_user.last_name %> </br>
  Mortgage Reference Number: <%= @current_user.mortgage_reference_num %></br>
<%= link_to 'Log Out', logout_path, method: :delete  %></p>

<% end %>

app/views/layouts/_navigation.html.erb
<div class="row">

  <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
         <li class="name">
           <h1 id="mytitle">Income & Expenditure </h1>
         </li>
         <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
 
        <section class="top-bar-section">       
          <ul class="right">
            <li><%= link_to 'Home', root_path %></li>
            <li><%= link_to 'About', static_pages_about_path %></li>
            <li><%= link_to 'Help', static_pages_help_path %></li>
          </ul>
        </section>
      
    </nav>

</div>
                   

   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= yield(:title) %> | Income & Expenditure</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

   <body>
         <div class ="row">
           <div class="small-11 small-centered large-10 large-centered  columns">
             <header>
              <%= render 'layouts/navigation' %>
             </header>

             <div class="row", id="innerpage">
               <%= render 'layouts/messages' %>
               <div class="container">
                  <% flash.each do |message_type, message| %>
                  <div class="alert alert-<%= message_type %>"><%= message %></div>
                  <% end %>
              </div>

               <%= yield %>

             </div>

           </div>
         </div>
         <%= render 'layouts/footer' %> 
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<div>
  <h1>Income & Expenditure Capture Service</h1>
<h2>About this site</h2>
<p>General bank information here.....</p>

<p>We have asked you to provide details of your income and expenditure so that we can better understand your ability to repay your mortgage.  Once you sign in, you can save your information, and return at any time to complete the form.  You can submit the form when you are ready.</p>

<p>If you need assistance completing the form, please click on the help option in the menu at any time</p>

<%= link_to 'back', :back %>

</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div>
  <h1>Income & Expenditure Capture Service</h1>
  <h2>Assistance Completing Your Form</h2>

<p>If you require assistance completing your form, we can do this together over the phone.  Please contact us on xxxxxxxxx, quoting your mortgage reference number.</p>

<p>If you would like to provide extra information in your form, there is a 'Notes' section for you to complete before you submit you details. </p>

<%= link_to 'back', :back%>

</div>

app/views/users/_usermessages.html.erb
<% if @user.errors.any? %>

The form contains <%= pluralize(@user.errors.count, "error") %>

<%end%>